Update fr translations
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #1061
Opened 2024-04-20 09:07 UTC by florentdordaquy

Hello,

Here is all the missing translations.
Sorry for the delay 

Merci :)

2024-04-20 09:49 UTC, RaenonX requested changes
Remember to just amend your last commit, so all the translations are in the same commit

2024-04-20 09:49 UTC, RaenonX commented on messages/ui-fr.json
> -            "Auto": "Auto recipe mode ignores the given cooking schedule, but respects the recipe levels. It finds the best cooking schedule and the team using the given recipe levels instead. As a r
Shouldn't have extra space after `"Auto"`

2024-04-20 09:49 UTC, RaenonX commented on messages/ui-fr.json
> -          "RatingResultsStoredOnline": "Premium users can have their rating results persisted online for the same build to save repetitive computation. [Get Premium Now!](https://pks.raenonx.cc/en/do
Does French separate punctuations (`!` here) with word like `maintenant !`, or it's `maintenant!`?

2024-04-20 10:01 UTC, florentdordaquy commented on messages/ui-fr.json
> -          "RatingResultsStoredOnline": "Premium users can have their rating results persisted online for the same build to save repetitive computation. [Get Premium Now!](https://pks.raenonx.cc/en/do
Yes, there is a space before and after the !, it's the same for : ; « » and also math symbols

2024-04-20 21:15 UTC, RaenonX commented
@florentdordaquy Remember to push your change, in case you forgot :)

2024-04-28 06:05 UTC, RaenonX approved these changes

2024-04-28 06:23 UTC, merged