Added ingredient total #311
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #340
Opened 2023-10-10 18:34 UTC by benginerd

Closes #311

2023-10-10 19:07 UTC, RaenonX requested changes

2023-10-10 19:07 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +          {quantity}
Since this is a floating number, use `formatFloat()`

Basically when rendering a number, unless it's always a small integer (ingredient count, carry limit), use number formatter (`format*` series that handles number formatting, in the same ts file) to ensure it's getting properly formatted.

2023-10-10 19:07 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/main.tsx
> +        showQuantity={true}
No `={true`, simply list out the attribute

Whenever an attribute is true, it's always just a name there like how `noFullWidth` is called.

2023-10-10 19:08 UTC, RaenonX commented
Mention that the change is in team analysis as well in the commit message

2023-10-11 16:14 UTC, benginerd commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +  const visibility = showQuantity ? 'visible' : 'hidden';
Agreed. My original thinking was this method maintained the spacing for the berry results, but we as discussed, we are instead moving the ingredient total to its own line.

2023-10-12 01:28 UTC, RaenonX requested changes

2023-10-12 01:28 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +      <Flex direction="row" className="md:flex-col" center noFullWidth>
I usually put `className` to the last, so if it requires line-break (need to call `clsx()`), everything else stays at the line with `<Flex`

2023-10-12 01:28 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +        <div className='text-sm'>
Always use double quote JSX attribute

2023-10-12 01:28 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +        {showQuantity &&
Line break doesn't look right to me
You have a line break at L34 but not here

2023-10-12 01:28 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +        }
Bracket positioning doesn't look right to me, check how other brackets are aligning.

Searching using `&&` should give you some ideas

2023-10-12 01:28 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +      <Flex direction="row" center wrap className="gap-1">
Not sure if this duplicated `<Flex>` call is intended.
This looks like it's creating additional `<Flex>`.

2023-10-12 01:53 UTC, RaenonX requested changes

2023-10-12 01:53 UTC, RaenonX commented on src/ui/team/analysis/setup/summary/grouped/category.tsx
> +      <Flex direction="row" center noFullWidth className="md:flex-col" >
No space here -> `" >`

2023-10-12 01:56 UTC, RaenonX approved these changes

2023-10-12 02:09 UTC, merged