Added sleep style counter to pokemon info page #263
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #568
Opened 2023-12-08 17:58 UTC by benginerd

Revolves #263 

Looking for guidance on formatting lines 37 and 47 so they're shorter. 

This implementation uses `SleepStyleNormal` and `SleepStyleSpecial` to record the Pokemon's individual total sleep styles and the user's unlocked sleep styles for it. If there exists a better type to determine this information, then I will refactor this.

2023-12-09 02:14 UTC, RaenonX requested changes

2023-12-09 02:14 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +  const unlockedSleepStyles: SleepStyleId[] = [];
`sleepStylesNormal` and `sleepStylesSpecials` are guaranteed to be mutually exclusive, so you can just grab the style ID from both, merge it, then check.

Note, `map()` usage here is not ideal here, becuase `.map()` indicates that you will use the return value, but here you are not. Try creating the result using a single `reduce()` call. If in question, check the `reduce()` impl in the repo first.

2023-12-12 02:48 UTC, RaenonX requested changes

2023-12-12 02:48 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +  const totalSleepStyles = toUnique([
There's no `count` concept here, so naming it as `total*` is a bit weird. I would name it just `sleepStyles` or `availableSleepStyles`.

2023-12-12 02:48 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +  const unlockedSleepStyles = totalSleepStyles.reduce((unlockedSleepStyles:number, current) => {
No need to type that `unlockedSleepStyles` here. If you need to type it, it's gonna be `variable: number` (note the space).

2023-12-12 02:48 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +    isInSleepdex({sleepdex, pokemonId: pokemon.id, styleId: current}) ? unlockedSleepStyles++ : unlockedSleepStyles;
This along with L43 seems really weird to me. I know what you're doing, but it should be just add 1 to the original then return, or simply return the original.

2023-12-12 14:53 UTC, benginerd commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +  const unlockedSleepStyles = totalSleepStyles.reduce((unlockedSleepStyles:number, current) => {
When it isn't typed, I receive an `An arithmetic operand must be of type 'any', 'number', 'bigint' or an enum type.` error, since `.reduce()` was not seeing the initialValue of 0 as a number for some reason.

2023-12-12 15:00 UTC, benginerd commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +    isInSleepdex({sleepdex, pokemonId: pokemon.id, styleId: current}) ? unlockedSleepStyles++ : unlockedSleepStyles;
By original do you mean the accumulator? I may be misunderstanding, but I believe `.reduce()` uses array[0] for the accumulator if an initialValue is not specified, so I tried to make the accumulator a number that starts at 0. Otherwise it tells gives me the error in my last comment, or it says `Operator '+' cannot be applied to types 'string | number' and 'number'`

2023-12-12 15:45 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +  const unlockedSleepStyles = totalSleepStyles.reduce((unlockedSleepStyles:number, current) => {
Try changing the whole impl, seems my TS can implicitly type if 
![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/32151063-b265-4c1b-8a5c-70e874abcdd0)

2023-12-12 15:46 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +    isInSleepdex({sleepdex, pokemonId: pokemon.id, styleId: current}) ? unlockedSleepStyles++ : unlockedSleepStyles;
![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/03016944-ae50-4604-9e83-7a86d4cd39c0)

2023-12-12 19:56 UTC, benginerd commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +    isInSleepdex({sleepdex, pokemonId: pokemon.id, styleId: current}) ? unlockedSleepStyles++ : unlockedSleepStyles;
https://stackoverflow.com/questions/73879488/cant-apply-reduce-on-array-of-numbers-or-nulls

This stackoverflow seems to explain why it can implicitly type `accumulator` but encounters issues since `SleepStyleId` is defined as `number | 'onSnorlax'`. `SleepStyleId`'s typing may not trigger any errors when initialValue is set to 0, but then doesn't like possibly being a string too. So manually defining the accumulator as `number` seems to avoid this possibility. 

If this is correct, we could opt for `unlockedSleepStyles: number` or change the `reduce()` call to `reduce<number>()`. This seems to fix the issue. 

Since `SleepStyleId` seems to be the cause of the problem, changing `totalSleepStyles` to `string[]` instead of `SleepStyleId[]` would fix the accumulator problem - but it would make `current` into a string type by default instead of `SleepStyleId`. `isInSleepdex()` needs a `SleepStyleId` for `styleId`, so based on this information, it's making me think `: number` or `reduce<number>` is the way to go. 

Let me know what you think. I agree the if statement looks better than the ternary, so I fixed that.^^

2023-12-12 20:21 UTC, RaenonX commented on src/ui/pokedex/page/sleepStyle/loaded.tsx
> +    isInSleepdex({sleepdex, pokemonId: pokemon.id, styleId: current}) ? unlockedSleepStyles++ : unlockedSleepStyles;
Did you push the change? Not seeing any change here

2023-12-13 08:38 UTC, RaenonX approved these changes

2023-12-13 08:39 UTC, RaenonX requested changes
Check CI error and fix it

2023-12-13 20:44 UTC, RaenonX requested changes
Include `closes #263` as the 3rd line of the commit message (2nd line is an empty line)
Rebase onto `origin/main`

This should be the last change needed

2023-12-14 18:35 UTC, merged