Performance Improvements with a focus on Team Analysis via PokéBox #429
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #625
Opened 2023-12-25 00:11 UTC by johnmgrant

* Fixed Image optimization warning...
  * Resolved warning with `3iggs.png`
  * next.js reference ([1](https://nextjs.org/docs/api-reference/next/image#priority), [2](https://github.com/vercel/next.js/discussions/48255))
* Fixed auto-scroll warnings
  * Resolved warnings related to links having no specification for scroll
  * TBD what links actually need [scroll to top on navigation](https://nextjs.org/docs/pages/api-reference/components/link#scroll-1).
  * Relates to [this comment on github](https://github.com/shadcn-ui/ui/issues/1355#issuecomment-1699784566).
* Updated `CanvasRenderingContext2D` objects...
  * to indicate frequently reading image processing for loading (i.e. ["will read frequently"](https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently))
* Improved performance for site by disabling [link prefetching](https://nextjs.org/docs/pages/api-reference/components/link#prefetch)
  * Will enable on a case by case basis moving forward
* Refactors team analysis logger to team utils and applies on dev builds.
* Added support for loading standalone react devTools for Safari debugging without [custom build setup](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/issues/496#issuecomment-1861804958)
  * https://github.com/vercel/next.js/discussions/50665
* Added support for VSCode workspace

2023-12-31 12:03 UTC, RaenonX commented
@johnmgrant 

Was gonna merge this, but didn't see `yarn run dev:debug-client` in `package.json`, did you forget to add it? You can just add `yarn run dev:debug-client` into `package.json` and amend the latest commit then force-push it.

Also, I modified some of your commits and rebased.

2023-12-31 12:05 UTC, RaenonX requested changes
Need `yarn run dev:debug-client` in `package.json`. I am thinking of naming it as `yarn run dev:react-devtools` if it's really just starting up React DevTools. You can just add the script of `dev:react-devtools` and change the content in `README.md` accordingly.

2023-12-31 22:22 UTC, RaenonX requested changes
You'll see a bunch of "Should be good to use <FlexLink/>." These are some other hopefully performance improvement, See #636 for details.

Also for #636, make it altogether an individual commit.

2023-12-31 22:22 UTC, RaenonX commented on package.json
> +    "dev:debug-server": "node --inspect=9229 ./node_modules/next/dist/bin/next",
Maybe make it consistent, like `dev:debug:server`, `dev:react-devtools`, and `dev:debug:client` or something similar?

Also put it right under `dev` `scripts`.

You can just squash this into the commit for React DevTools if those are all for it. If `dev:debug:server` and `dev:debug:client` are for VSCode, squash it into the VSCode commit instead.

2023-12-31 22:22 UTC, RaenonX commented on src/components/shared/link/feature.tsx
> +    <NextLink href={href} className={clsx(
Feels like this can actually use `<FlexLink/>`

This will be separate commit tho.

2023-12-31 22:22 UTC, RaenonX commented on src/components/shared/map/link.tsx
> +    <NextLink href={`/map/${toUnique ? 'unique/' : ''}${mapId}`} className={clsx(
Feels like this can use `<FlexLink/>` as well, but need to test.

2023-12-31 22:22 UTC, RaenonX commented on src/components/shared/meal/link.tsx
> +    <NextLink href={`/meal/${id}`} className={clsx(
Maybe can use `<FlexLink/>` as well.

2023-12-31 22:22 UTC, RaenonX commented on src/ui/auth/signIn/main.tsx
> +        <NextLink href={'/auth/sign-in/email'} className="border-link w-fit">
Should be good to use `<FlexLink/>`

2023-12-31 22:22 UTC, RaenonX commented on src/ui/berry/index/link.tsx
> +    <NextLink href={`/berry/${id}`} className="w-full">
Should be good to use `<FlexLink/>`

2023-12-31 22:22 UTC, RaenonX commented on src/ui/ingredient/index/link.tsx
> +    <NextLink href={`/ingredient/${id}`} className="w-full">
Should be good to use `<FlexLink/>`

2023-12-31 22:22 UTC, RaenonX commented on src/ui/ingredient/page/recipe.tsx
> +          <NextLink key={meal.id} href={`/meal/${meal.id}`}>
Should be good to use `<FlexLink/>`

2023-12-31 22:22 UTC, RaenonX commented on src/ui/meal/page/info.tsx
> +            <NextLink key={id} href={`/ingredient/${id}`} className="button-clickable-bg p-1.5">
Should be good to use `<FlexLink/>`

2023-12-31 22:22 UTC, RaenonX commented on src/ui/pokedex/page/production/ingredient/link.tsx
> +    <NextLink href={`/ingredient/${id}`} className="button-clickable-bg p-1.5">
Should be good to use `<FlexLink/>`

2024-01-01 16:13 UTC, johnmgrant commented on package.json
> +    "dev:debug-server": "node --inspect=9229 ./node_modules/next/dist/bin/next",
These aren't *required* by VSCode, but they are convenience for running tasks with shortcuts. I will update as you've requested.

2024-01-01 16:28 UTC, RaenonX requested changes
Add reference of the issue in the commit message like

```
Updated some `<NextLink/>` to `<FlexLink/>` #636

closes #636
```

2024-01-01 23:03 UTC, RaenonX commented
Oh btw, what I mean by using `<FlexLink/>` is to merge `<NextLink/>` with `<Flex/>`. So this should be `<FlexLink/>` then `children`. You might have to check if the style goes off by eyeballing once the change is made tho.

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/9607e6a3-8cfe-43cf-a73e-d87474f2d55f)

2024-01-02 03:24 UTC, johnmgrant commented on src/components/shared/meal/link.tsx
> +    <NextLink href={`/meal/${id}`} className={clsx(
This is the only one that didn't look right during testing when I tried to remove the inner Flex.

2024-01-02 04:07 UTC, RaenonX requested changes

2024-01-02 04:07 UTC, RaenonX commented on src/ui/auth/signIn/main.tsx
> +        <FlexLink href={'/auth/sign-in/email'} direction="row"
Make it like this
```typescript
<FlexLink
  href="/auth/sign-in/email"
  direction="row"
  noFullWidth
  center
  className="border-link w-fit gap-1.5"
>
```

My logic behind is:
- When a string attribute is constant, then it should be `attribute="value"` not`attribute={`value`}`.
- When all attributes can't fit in 1 line, if it has `className`, then use `clsx()` to break its line. If every non-className attributes already make the width getting closer to the line length limit, break all of the with 2-space indent to the parent. This is the logic used here.

2024-01-02 04:07 UTC, RaenonX commented on src/ui/berry/index/link.tsx
> +      <div key={id} className={clsx(
Shouldn't need this `<div>` and no need to have `key` here.

`<FlexLink/>` is a `<NextLink/>` which is basically an `<a>` using `display: flex`. So everything of this `<div>` should be able to be on `<FlexLink/>`.
Or, if there's that SVG rendering bug (which shouldn't happen here?), then it should be `<Flex/>`. `getFlexStyles()` is not intended to be called outside of some base HTML wrapper component impl.

Might have to change this on every link touched because I am seeing bunch of `getFlexStyles()` usages.

2024-01-02 04:07 UTC, RaenonX commented on src/ui/pokedex/page/production/ingredient/link.tsx
> -    <Link href={`/ingredient/${id}`} className="button-clickable-bg p-1.5">
Should be just `<FlexLink>` instead of `<FlexLink>` then `<div>`

2024-01-02 04:17 UTC, johnmgrant commented on src/components/shared/link/main.module.css
> +    @apply p-0.5 h-28 w-full overflow-hidden;
With the `block` left in, it wasn't flex and the icons on the homepage were fixed to the top right corner.

2024-01-02 04:20 UTC, RaenonX commented on src/components/shared/link/main.module.css
> +    @apply p-0.5 h-28 w-full overflow-hidden;
Oh I see, good to keep this 👍

2024-01-02 04:21 UTC, johnmgrant commented on src/ui/berry/index/link.tsx
> +      <div key={id} className={clsx(
When I removed the Flex, the styles broke for this component. I tried getting them to group the same beneath the single link, but I will try again after this recent feedback.

2024-01-02 04:28 UTC, RaenonX commented on src/ui/berry/index/link.tsx
> +      <div key={id} className={clsx(
OK, if it breaks, maybe it's some styling issue, unless SVG doesn't render.

These are some styling classes or props I commonly use:

`<Flex*/>` component attributes:
- `center` is the shorthand of centering everything. Use this only if you really wants everything centered, including the children. Personally I use this only when it's 1 or 2 layer deeper and the implementation is simple. 
- `direction` can be either `col` or `row`. `<Flex/>` defaults to `col` and `<FlexButton/>` defaults to `row`. Maybe check component implementation for the actual default value. `<FlexLink/>` is and should default to `row`.
- Some `<Flex*/>` components default to full width (using `w-full`), especially `<Flex/>`. In some cases, `noFullWidth` is needed as full width isn't desired. Note, some `<Flex*/>` has this default to `false`.

Tailwindcss classes I use frequently:
- `items-center` for centering items when `<Flex/>` `direction` is `row` to vertically center stuff
- `justify-center` for horizontal center in `direction` of `col`
- `gap-*` for adjusting the gap between the direct child of `<Flex*/>`

See if these help you fix the styling. If not, send me a screenshot and line number and I can take a look ;)

2024-01-03 00:09 UTC, RaenonX approved these changes
I fixed a few attribute quote inconsistencies, but other than that, all good, thanks! Hopefully this gives you a rough picture of the coding style and the repo structuring ;)

2024-01-03 00:29 UTC, merged