Updates PWA Icons #665
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #667
Opened 2024-01-06 18:27 UTC by johnmgrant

* Closes #665

2024-01-07 00:00 UTC, johnmgrant commented on tsconfig.json
> +    "strictFunctionTypes": true,
@RaenonX this one and maybe line 21 might be the cause for issue in tests.

2024-01-07 00:02 UTC, RaenonX commented on tsconfig.json
> +    "strictFunctionTypes": true,
I'll disable for now but I'd rather leave them on if possible

2024-01-07 00:09 UTC, RaenonX commented
Btw I'd like `tsconfig.json` to look similar like what it was, for example `es2022` instead of `ES2022` and line breaking every arrays `[]`.

2024-01-07 00:11 UTC, RaenonX commented on tsconfig.json
> +    "strictFunctionTypes": true,
Seems like the yarn cache I had was the issue, clearing everything then `yarn --immutable` works fine

2024-01-08 19:12 UTC, RaenonX requested changes

2024-01-08 19:12 UTC, RaenonX commented on next.config.js
> +const isProd = process.env.NODE_ENV !== 'development';
There's a `isProduction()` already available for this kind of check, I am not sure if that util is accessible here tho.

2024-01-08 19:12 UTC, RaenonX commented on public/manifest.json
> +    "寶可夢睡覺",
Not sure why there seems to be an additional space after comma `,` 

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/8ad82463-2b38-4b7f-954b-3642a844b71c)

2024-01-08 19:12 UTC, RaenonX commented on src/utils/meta.ts
> +      'msapplication-TileColor': '#ffffff',
Maybe change this to the lighter color theme in the sketch-like icon?

2024-01-08 19:12 UTC, RaenonX commented on tsconfig.json
> +    "allowJs": true,
What happens if `false`?

2024-01-08 19:12 UTC, RaenonX commented on tsconfig.json
> +    "moduleResolution": "Bundler",
What happens if not `Bundler` or preferrably `bundler` if it's valid?

2024-01-08 19:12 UTC, RaenonX commented on tsconfig.json
> +    "next-env.d.ts",
Somehow empty space after comma.

2024-01-08 19:15 UTC, johnmgrant commented on tsconfig.json
> +    "allowJs": true,
The build fails because the `threads` package needs to update the tsconfig for type support.

2024-01-08 19:18 UTC, RaenonX commented on tsconfig.json
> +    "allowJs": true,
Do you have `@types` installed (I would assume so though)? I've been using that package for a while with this being `false` and it didn't fail. Or is this related to other settings?

2024-01-08 19:18 UTC, johnmgrant commented on next.config.js
> +const isProd = process.env.NODE_ENV !== 'development';
I tried using it, but it wouldn't access it from the utils.

2024-01-08 19:19 UTC, johnmgrant commented on src/utils/meta.ts
> +      'msapplication-TileColor': '#ffffff',
Setting this to the same color that's used as the [theme_color](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/18a671eeeaa7826ec6651f7eac0fb9ce1300844f/public/manifest.json#L7-L8)

2024-01-08 19:20 UTC, RaenonX commented on next.config.js
> +const isProd = process.env.NODE_ENV !== 'development';
I see, all good then

2024-01-08 19:23 UTC, johnmgrant commented on tsconfig.json
> +    "moduleResolution": "Bundler",
I will revert this as it seems that `node` is more portable albeit at the cost of build time.

2024-01-08 19:25 UTC, RaenonX commented on tsconfig.json
> +    "moduleResolution": "Bundler",
Could you elaborate on portable part? I am fine keeping this since it saves about 3 mins for each build.

2024-01-08 19:27 UTC, johnmgrant commented on tsconfig.json
> +    "allowJs": true,
Checking again now :eyes:

2024-01-08 19:30 UTC, johnmgrant commented on tsconfig.json
> +    "allowJs": true,
It's working.. Not sure what happened last time. I'll revert this!

2024-01-08 19:37 UTC, johnmgrant commented on tsconfig.json
> +    "moduleResolution": "Bundler",
Sure. https://arc.net/l/quote/zcyruoin

Since this isn't meant as a library or to be bundled in another application, I think it's fine leaving it as a bundler.

2024-01-08 21:55 UTC, RaenonX requested changes

2024-01-08 21:55 UTC, RaenonX commented on package.json
> +    "webpack": "^5.89.0"
What if this isn't added? I thought `next` bundle it themselves already

2024-01-09 01:17 UTC, johnmgrant commented on package.json
> +    "webpack": "^5.89.0"
I was following the installation steps for [‎@ducanh2912/next-pwa](https://ducanh-next-pwa.vercel.app/docs/next-pwa/getting-started)

2024-01-09 03:06 UTC, RaenonX commented on package.json
> +    "webpack": "^5.89.0"
I guess removing the dependency should be fine? Give it a try

2024-01-09 04:20 UTC, RaenonX approved these changes

2024-01-09 04:30 UTC, merged

2024-01-09 10:16 UTC, RaenonX commented
@johnmgrant I'll revert `moduleResolution` back to `node` because that seems to be the root cause of the issue.

### When `bundler`

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/20ce00f3-28d3-458e-b762-a235c0a55870)

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/17b799c2-f0b6-43d2-a95d-1f5872e900ff)

### When `node`

(everything is fine)

2024-01-09 13:00 UTC, johnmgrant commented
> @johnmgrant I'll revert `moduleResolution` back to `node` because that seems to be the root cause of the issue.
> 
> 
> 
> ### When `bundler`
> 
> 
> 
> ![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/20ce00f3-28d3-458e-b762-a235c0a55870)
> 
> 
> 
> ![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/17b799c2-f0b6-43d2-a95d-1f5872e900ff)
> 
> 
> 
> ### When `node`
> 
> 
> 
> (everything is fine)

This is why I had `allowJS` set to true. By including having node as module resolution. https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/pull/667#discussion_r1445219241

If we're fine with longer build times for compiling all source for node resolution, then that's also fine with me. Just let me know 👍🏾

2024-01-09 15:05 UTC, RaenonX commented
> > @johnmgrant I'll revert `moduleResolution` back to `node` because that seems to be the root cause of the issue.
> > ### When `bundler`
> > ![image](https://private-user-images.githubusercontent.com/18443743/295173697-20ce00f3-28d3-458e-b762-a235c0a55870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTI4NzMsIm5iZiI6MTcwNDgxMjU3MywicGF0aCI6Ii8xODQ0Mzc0My8yOTUxNzM2OTctMjBjZTAwZjMtMjhkMy00NThlLWI3NjItYTIzNWMwYTU1ODcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE1MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzM2ViMmZjZmMxODlkN2Y0YjBhOTUwMDljMjNmYmY1YmMwYTMxMTk2ZWZmMmM0YTY1ZDBkNWE0NjU2YzgxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wwIlFESvSTMEXz4GbPxdGi-2DYcdAlt9sU4jAqPM1Qg)
> > ![image](https://private-user-images.githubusercontent.com/18443743/295173744-17b799c2-f0b6-43d2-a95d-1f5872e900ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTI4NzMsIm5iZiI6MTcwNDgxMjU3MywicGF0aCI6Ii8xODQ0Mzc0My8yOTUxNzM3NDQtMTdiNzk5YzItZjBiNi00M2QyLWE5NWQtMWY1ODcyZTkwMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE1MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNGYwNzMyMTYwZDc5MWIxODU2YTllNjUwMjViODM3YTNkZmM1Yjk2MjNmMjJiM2IyZWQwMDczOGI1MGQzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BB752VC6dPV1FcZqWdhqumKLF6VkakFvt5M5GiKTe-I)
> > ### When `node`
> > (everything is fine)
> 
> This is why I had `allowJS` set to true. By including having node as module resolution. [#667 (comment)](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/pull/667#discussion_r1445219241)
> 
> If we're fine with longer build times for compiling all source for node resolution, then that's also fine with me. Just let me know 👍🏾

I noticed that worker pool from `threads` will fail to infer some types, so I reverted it in f8ca061749437a4396d6a93121218366c75ac30b. Think it's a bit risky to let it infer any in exchange of build time. I'll check (or maybe you check) to see if allowJs can be turned off again.