Added PWA Social Share Metadata
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #684
Opened 2024-01-14 16:51 UTC by johnmgrant

2024-01-14 17:03 UTC, RaenonX requested changes

2024-01-14 17:03 UTC, RaenonX commented on src/utils/meta.ts
> +    metadataBase: new URL(`${process.env.NEXTAUTH_URL}`),
Should be able to just `new URL(process.env.NEXTAUTH_URL)`? Don't think an additional template string is needed

2024-01-14 17:10 UTC, johnmgrant commented on src/utils/meta.ts
> +    metadataBase: new URL(`${process.env.NEXTAUTH_URL}`),
Then I get a type error, so I thought best way was to just use it as template string.
![Screenshot 2024-01-14 at 12 10 01 PM](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/10672193/92c47a66-21d5-4ca3-84a4-06e7d3dc275a)

2024-01-14 22:22 UTC, RaenonX commented on src/utils/meta.ts
> +    metadataBase: new URL(`${process.env.NEXTAUTH_URL}`),
Undefined means the environment variable is not set, so if it's critical then throw an error, or just show a warning and set this field as null (default value).

2024-01-14 23:12 UTC, RaenonX requested changes

2024-01-14 23:12 UTC, RaenonX commented on src/utils/meta.ts
> +  const site = process.env.NEXTAUTH_URL ? process.env.NEXTAUTH_URL : 'https://pks.raenonx.cc';
Oh, I mean since the default value of `metadataBase` is `null` or `undefined`, if `process.env.NEXTAUTH_URL` is undefined, then `site` should still be undefined, so L20 should be `process.env.NEXTAUTH_URL ? new URL(process.env.NEXTAUTH_URL) : null` instead. Or if it accepts `string` and some nullish value, it's even better because we can just make it `process.env.NEXTAUTH_URL ?? null` or even just `process.env.NEXTAUTH_URL`.

2024-01-14 23:19 UTC, johnmgrant commented on src/utils/meta.ts
> +  const site = process.env.NEXTAUTH_URL ? process.env.NEXTAUTH_URL : 'https://pks.raenonx.cc';
URL cannot be null. How is it now?

2024-01-14 23:20 UTC, RaenonX commented on src/utils/meta.ts
> +  const site = process.env.NEXTAUTH_URL ? process.env.NEXTAUTH_URL : 'https://pks.raenonx.cc';
Not making a `new URL()` null, it's setting a nullish value to `metadataBase` like default, so it's either passing a URL to `metadataBase` or nothing/default.

2024-01-14 23:27 UTC, RaenonX requested changes

2024-01-14 23:27 UTC, RaenonX commented on src/utils/meta.ts
> +  const site = process.env.NEXTAUTH_URL ? process.env.NEXTAUTH_URL : '';
Think this can merge into `metadataBase` (literally replace all `site` usages) if only referred once, then once replaced should be all good

2024-01-14 23:38 UTC, RaenonX approved these changes

2024-01-15 00:04 UTC, merged

2024-01-15 01:55 UTC, julius911 reviewed
Rational

2024-01-15 01:55 UTC, julius911 approved these changes