Resolved PWA Inconsistencies #693
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #716
Opened 2024-01-24 01:34 UTC by johnmgrant

Closes https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/issues/693

Improved VSCode development utils
* Updated ESLint to support formatting JSON files
* Added prettier format rules through VSCode prior to ESLint for code wrapping.
* Configured typescript override
* Added https experimental support

Configured dynamic manifest
* Modified Manifest to support localization
* Updated PWA to support offline experience
* Update device icon support

Fixed theme color inconsistency between system, site and PWA

2024-01-24 03:05 UTC, RaenonX requested changes

2024-01-24 03:05 UTC, RaenonX commented on src/utils/meta.ts
> +        'en': '/en',
Make string keys simply literal key (same coloring stuff mentioned above).

Also use `satisifes` to type this object `{[locale in Locale]: string}` so when new locale is added, then this object pops error.

2024-01-24 03:05 UTC, RaenonX commented on src/utils/meta.ts
> +  t: (key: I18nMessageKeysOfNamespace<'UI.Metadata'>) => string;
`,` comma instead of `;` for consistency

2024-01-24 03:05 UTC, RaenonX commented on src/utils/metadata.ts
> +}: {
Type the parameter as `GenerateSiteMetadataOpts` instead.

2024-01-24 03:05 UTC, RaenonX commented on src/utils/metadata.ts
> +  values = undefined,
If `values` is `undefined` then it's gonna be `undefined`, so I don't think a default value assignment is needed here?

2024-01-24 03:05 UTC, RaenonX commented on src/utils/metadata.ts
> +      return {
If it's single line return, make it like this instead:
```typescript
.map(() => ({
  a: 'b',
})
```

2024-01-24 03:05 UTC, RaenonX commented on src/utils/metadata.ts
> +            'name': t('Home.Title'),
Make this literal key instead of string key.

2024-01-24 21:43 UTC, johnmgrant commented on src/utils/manifest.ts
> +    // @todo: make this generative of images instead.
Created #723

2024-01-24 21:51 UTC, johnmgrant commented on src/utils/manifest.ts
> +  return {
Updating ESLint to contain the following rule then.
```
  quote-props:
    - error
    - "as-needed"
    - keywords: true
      unnecessary: true
```

2024-01-24 21:55 UTC, johnmgrant commented on src/ui/base/navbar/darkMode/main.tsx
> +  const {resolvedTheme: theme, setTheme} = useTheme();
`theme` initially defaults to 'system' on first user visit where as `resolveTheme` utilizes session object defined [here](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/blob/fa54381040dcf3e7dfb4668006fade9febf86bc5/src/ui/base/providers.tsx#L21-L22) to always return either `light` or `dark`. The result is that the site defaults to the users device settings and only if the theme icon is selected will that be overridden and persist to the PWA.

2024-01-24 23:08 UTC, johnmgrant commented on messages/ui-kr.json
> +      "Description": "포켓몬 슬립 위키는 포켓몬의 수면 정보, 레시피, 식재료, 나무열매 뿐 아니라 팀 분석, 포켓몬 EXP 계산과 같은 툴을 포함한 다양한 정보와 기능을 제공합니다.",
I think it just added a trailing comma here, but I reached out about the "Guide" translation.

2024-01-25 18:07 UTC, johnmgrant commented
Closing this as it no longer would address #693. 

Breaking out the changes to individual issues.

2024-01-25 18:07 UTC, closed without merging