Updated KR translations
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #777
Opened 2024-02-04 11:21 UTC by psp0

hello! This PR added some KR translations.

I translated it with consideration to the extent of my knowledge.
Even though the content is small, I hope it is helpful.

I would appreciate it if you could check out these changes.
thanks~

2024-02-04 11:37 UTC, RaenonX requested changes

2024-02-04 11:37 UTC, RaenonX commented on messages/ui-kr.json
> +      "Title": "비교중...",
This can be something 비교 대상 if you find it appropriate because this is the text in the rating page that allows you to select what group of Pokemon to compare

2024-02-04 12:05 UTC, psp0 commented
Oh I got it. This part is something I don't know much about, so I'll put it back.

2024-02-04 16:19 UTC, RaenonX requested changes
![Screenshot_20240204_101754_Edge](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/b65084ef-5341-4171-94ef-af63fc777ac0)

It's this one. Also squash all commits into 1. No need to worry about force push because only the code in main branch gets deployed

2024-02-05 12:04 UTC, psp0 commented
I squashed it and force-pushed it. I hope I did well. 🙂

2024-02-05 12:05 UTC, RaenonX commented
> I squashed it and force-pushed it. I hope I did well. 🙂

When there's new commit coming in, use rebase instead - so this commit 526f1803bcf5d5d8efd8a355f341ca72313b6a96 shouldn't be on the history, then it should be all good!

2024-02-05 12:46 UTC, merged