Added staged lint support #727
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #778
Opened 2024-02-04 17:14 UTC by johnmgrant

Closes #727

2024-02-05 02:08 UTC, RaenonX requested changes

2024-02-05 02:08 UTC, RaenonX commented on yarn.lock
This could be accidental push? Yarn v4 shouldn't have this

2024-02-05 22:49 UTC, johnmgrant commented on yarn.lock
I'm not entirely sure what this was referring to, so you'll have to let me know if it's still not fixed.

2024-02-06 07:40 UTC, RaenonX commented on yarn.lock
nvm I brain farted

2024-02-06 07:44 UTC, RaenonX requested changes

2024-02-06 07:44 UTC, RaenonX commented on .prettierrc.json
> +        "printWidth": 69,
Think I actually set it to 119 in ESLint, will this conflict with that?

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/078a8be3-fb7f-4293-9399-dc3ee613a129)

Also this seems inconsistent with the 80 in L7

2024-02-06 07:44 UTC, RaenonX commented on lint-staged.config.js
> +const getFileList = (filenames) =>
I would make this 
```javascript
const currentWorkingDir = process.cwd();

const getFileList = (filenames) => filenames
  .map((f) => path.relative(currentWorkingDir, f))
  .join(' --fix --file ');
```

If this doesn't have any issue for clarity and possibly less `cwd()` checks

2024-02-06 07:44 UTC, RaenonX commented on lint-staged.config.js
> +const eslintCommand = (filenames) =>
If this can't fit the max line width of 119 then
```javascript
const eslintCommand = (filenames) => (
  `next lint --fix --file ${getFileList(filenames)}`
);
```

2024-02-06 07:44 UTC, RaenonX commented on lint-staged.config.js
> +module.exports = {
Space in-between this and `stylelintCommand`

2024-02-06 10:47 UTC, johnmgrant commented on .prettierrc.json
> +        "printWidth": 69,
This is an override value, so no conflict with L7. Also, it doesn't apply to eslint since we aren't using prettier rules in eslint. I have this set lower to help with line wrappings since Eslint doesn't handle those well, but maybe the new rules I added will help. 

I'll bump everything to be consistent.

2024-02-06 10:48 UTC, RaenonX commented on .prettierrc.json
> +        "printWidth": 69,
Oh didn't notice it's override, I think json is find having 80 or even 119

2024-02-06 13:33 UTC, johnmgrant commented on lint-staged.config.js
> +module.exports = {
Added eslint rules for `padding-line-between-statements`

2024-02-06 13:40 UTC, RaenonX commented on lint-staged.config.js
> +module.exports = {
Thank you eslint pro

2024-02-06 13:56 UTC, johnmgrant commented on .prettierrc.json
> +        "printWidth": 69,
Changing it in prettier causes it to pull lines up to fill the 119 max-len, so I've reverted this to the default 80 for now.

2024-02-06 13:58 UTC, johnmgrant commented on lint-staged.config.js
> +const eslintCommand = (filenames) =>
I haven't found a rule for this yet, but i think the rules I've tried could also be in conflict with something else defined by one of the plugins. Might create a separate issue for this, but I'll log in the discord thread for now.

2024-02-06 21:17 UTC, RaenonX commented
I can smell that something about line break is breaking stuff lol

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/2fd621dd-5f60-48d6-8086-3d7d6c31ba4e)

2024-02-06 23:57 UTC, johnmgrant commented
> I can smell that something about line break is breaking stuff lol
> 
> ![image](https://private-user-images.githubusercontent.com/18443743/302779365-2fd621dd-5f60-48d6-8086-3d7d6c31ba4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNjQwNTksIm5iZiI6MTcwNzI2Mzc1OSwicGF0aCI6Ii8xODQ0Mzc0My8zMDI3NzkzNjUtMmZkNjIxZGQtNWY2MC00OGQ2LTgwODYtM2Q3ZDZjMzFiYTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDIzNTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OTIxMzhhYTc4YzYwMDBlZWQ3MGEwYzc3YmIzZmU5MTUzN2FlZmE2YzVkZGJlNTA5YWZhYmM1ODJhOGY4YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vNJpKhzy1r3mKVKqk4NkJwYtrbdNFg8jRotWzkfhQjQ)

I mostly wanted to see if the CI would run. I'll move this out for a separate issue though since I see some of the rules aren't quite right for the JSON as well.

2024-02-07 01:47 UTC, RaenonX requested changes

2024-02-07 01:47 UTC, RaenonX commented on .eslintrc.yml
> +      ignorePattern: "^\\s*import\\s.+from "
imports should be good to keep this rule as well? Like long import will make it something like this

![image](https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/assets/18443743/f20f30e7-ea67-4b65-b9be-3a245ecb0b40)

2024-02-07 01:47 UTC, RaenonX commented on src/utils/metadata.ts
> +  namespace: 'UI.Metadata'})
Weird linebreak here

2024-02-08 03:25 UTC, RaenonX approved these changes

2024-02-08 03:25 UTC, merged