Updated PWA Runtime Caching
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #803
Opened 2024-02-12 21:52 UTC by johnmgrant

follow-up for #799 

* Updated PWA runtime caching to default to `CacheFirst` for certain rules.
* Started to break next-config out into a package for the workspace
* Optimized Lint Step
  * Included [concurrently](https://www.npmjs.com/package/concurrently) package to run `next lint` commands by extension type
  * Updated package.json for peer dependencies
  * Updated lint-staged to use `eslint` for files outside of `src` dir and `next lint` otherwise.

2024-02-15 07:59 UTC, RaenonX requested changes

2024-02-15 07:59 UTC, RaenonX commented on lint-staged.config.js
> +const micormatch = require('micromatch');
`micromatch`

2024-02-15 07:59 UTC, RaenonX commented on lint-staged.config.js
> +const getFileList = (filenames, isNextLint) => filenames
Is it possible to type these despite in JS? Like typing `filenames` or any other function args.

2024-02-15 07:59 UTC, RaenonX commented on package.json
> +  "contributors": [
Add meeee
`RaenonX` and `raenonx0710@gmail.com`

2024-02-15 07:59 UTC, RaenonX commented on package.json
> +    "@types/micromatch": "^4",
Make it having full version number i.e. `^4.A.B`

2024-02-15 07:59 UTC, RaenonX commented on package.json
> +    "@types/prop-types": "^15",
Make it having full version number i.e. `^15.A.B`

2024-02-15 07:59 UTC, RaenonX commented on package.json
> +    "react-native": "^1000.0.0",
I can't tell if this is real or placeholder....

2024-02-15 07:59 UTC, RaenonX commented on packages/next-config/package.json
> +    {
Add meeeee

2024-02-15 09:47 UTC, johnmgrant commented on lint-staged.config.js
> +const getFileList = (filenames, isNextLint) => filenames
I'll see what I can do. Typically, you cannot use static types in JavaScript, so that's partly why I broke out a separate package to build the TS for the next-config.. There are ways around this though like using JSDoc and the ts-check, but I think JSDoc is actually what we want to use in this case.

2024-02-15 09:49 UTC, RaenonX commented on lint-staged.config.js
> +const getFileList = (filenames, isNextLint) => filenames
Let's go JSDoc is fine for me, you can pick whatever you think it helps explains the typing here.

2024-02-15 09:49 UTC, johnmgrant commented on package.json
> +    "@types/micromatch": "^4",
This was automatically applied on `yarn add ...`, but I'll update!

2024-02-15 09:49 UTC, johnmgrant commented on package.json
> +    "@types/prop-types": "^15",
This was automatically applied on `yarn add ...`, but I'll update!

2024-02-15 09:51 UTC, johnmgrant commented on package.json
> +    "react-native": "^1000.0.0",
This was automatically applied on `npx check-peer-dependencies --yarn --install`.

2024-02-15 11:07 UTC, RaenonX commented on package.json
> +    "react-native": "^1000.0.0",
Alright then, that `react-native` of v1000 astonished me. I can't tell if we really need these although they're listed as peer deps.

2024-02-17 15:46 UTC, johnmgrant commented on package.json
> +    "react-native": "^1000.0.0",
I'll remove the peer dependencies that we don't actively need in the source.

2024-02-17 23:27 UTC, RaenonX approved these changes

2024-02-17 23:45 UTC, merged