Updated KR translations
RaenonX-PokemonSleep/pokemon-sleep-ui pull request #944
Opened 2024-03-19 06:53 UTC by psp0

😵‍💫(I don't know how to deal with white-space. but If you only allow changes, tell me. Then I'll try to fix it as much I can.)

2024-03-19 23:09 UTC, RaenonX commented
Rebase all then it should be good

2024-03-20 05:20 UTC, psp0 commented
I just compared it after overwriting.

2024-03-20 05:40 UTC, RaenonX requested changes

2024-03-20 05:40 UTC, RaenonX commented on messages/ui-kr.json
> +    "DrowsyPower": "에너지 x 스코어 x **추가 졸음 파워 보너스(%)**",
Remove the `**` as the text won't be formatted

2024-03-20 06:03 UTC, psp0 commented on messages/ui-kr.json
> +    "DrowsyPower": "에너지 x 스코어 x **추가 졸음 파워 보너스(%)**",
ah I thought it'll be able to highlight.😅

2024-03-20 06:21 UTC, RaenonX approved these changes

2024-03-20 06:21 UTC, merged